<a href="https://colab.research.google.com/github/FARDIN98/AI-lab/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived object(such as masked arrays and matrics) and an assortment of routines for fast operations on arrays including mathmetical, logical, shape manipulation, sorting, selecting, I/Q, discrete fourier transforms.



In [2]:
#importing the numpy module
import numpy as np
#empty array
arr1=np.empty((4,5,2))
print(arr1)

[[[2.22067883e-316 0.00000000e+000]
  [3.57269797e-263 3.06694704e-314]
  [4.58987690e-311 7.87009235e-251]
  [5.54125273e-302 0.00000000e+000]
  [8.81442589e-280 8.73990206e+245]]

 [[7.85077093e+122 5.83336491e-302]
  [1.64290199e-287 4.43882662e-301]
  [1.98544252e-263 5.59923516e-249]
  [4.44611785e-301 6.75611097e-225]
  [1.90829145e-210 4.45340908e-301]]

 [[2.29898549e-186 6.50368725e-172]
  [4.46070032e-301 7.46897930e-301]
  [2.68196195e-297 4.76349988e-287]
  [3.01378736e-282 1.63423933e-301]
  [7.90684955e-148 7.65498426e-297]]

 [[2.50686974e-292 1.55896071e-307]
  [1.78019083e-306 2.62430329e-139]
  [7.22769604e+159 2.60985689e+180]
  [1.67793063e+243 3.17095867e+180]
  [4.53144912e+217 2.82875490e-110]]]


In [ ]:
#zeros
arr2=np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones
arr3 = np.ones((3,2))
print(arr3)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#prefilled up
arr4 = np.full((3,2),-1000)
print(arr4)

[[-1000 -1000]
 [-1000 -1000]
 [-1000 -1000]]


In [ ]:
#identity matrix
'''
[[1,0,0],
 [0,1,0],
 [0,0,1]
 ]
'''

arr5 = np.identity(4)
print(arr5)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#manual array build up

arr6 = np.array([[1,2,3],
                 [4,5,6]])
print(arr6)

arr7 = np.array([1,2,3], dtype=float)
print(arr7)

[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


In [ ]:
#array from a range value
arr8=np.arange(1,100,3) #upto 99
print(arr8)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [ ]:
#array from a range value
arr9 = np.linspace(0,1,35) #will generate 35 equidistant number from 0 to 1
print(arr9)

[0.         0.02941176 0.05882353 0.08823529 0.11764706 0.14705882
 0.17647059 0.20588235 0.23529412 0.26470588 0.29411765 0.32352941
 0.35294118 0.38235294 0.41176471 0.44117647 0.47058824 0.5
 0.52941176 0.55882353 0.58823529 0.61764706 0.64705882 0.67647059
 0.70588235 0.73529412 0.76470588 0.79411765 0.82352941 0.85294118
 0.88235294 0.91176471 0.94117647 0.97058824 1.        ]


In [5]:
#manual array build up

myarr=np.array([[1,2,3],
                [4,5,6]]) #array function returns an array type object

print(myarr)
#----------------------------------------------------------------------

print(myarr.ndim) #ei array te koto dimension er sheta dekhabe
print(myarr.shape) #ram ber korte shape use hoy
print(myarr.size) #total koyta element ase sheta ber korte size use hoy
print(myarr.dtype) #array er data type ber korte use hoy
print(myarr.T) #return the transpose matrix

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
[[1 4]
 [2 5]
 [3 6]]


In [6]:
#calculation
#default: numpy array works element-wise = broadcasting(reduces number of for loop)

arr1=np.array([[1,2,3,4],
               [5,6,7,8]])

print(arr1 + 10)

[[11 12 13 14]
 [15 16 17 18]]
